# Generated by Django 2.1.5 on 2019-01-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Product',
        ),
    ]
